swagger: "2.0"
info:
  description: "oliveサロンのフロントエンドで必要なAPIです"
  version: "1.0.0"
  title: "oliveサロンフロントエンドAPI"
  termsOfService: "https://github.com/egg-system/olive-front"
  contact:
    email: "example@example.com"
  license:
    name: "エッグシステム"
    url: "https://eggsystem.co.jp/"
host: "reserve.olivebodycare.healthcare"
paths:
  /pet/{petId}:
    get:
      tags: ["shun API"]
      summary: "ペット情報API"
      description: "指定されたpetIdの情報を返します"
      parameters:
      - name: "petId"
        in: "path"
        description: "取得したいペットのID"
        required: true
        type: "integer"
        format: "int64"
      - name: "petId2"
        in: "query"
        description: "取得したいペットのID2"
        required: false
        type: "integer"
        format: "int"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
              product:
                properties:
                  id: 
                    #データ型
                    type: "integer"
                    #ダミー値
                    example: "1"
                  name:
                    type: "string"
                    example: "hogehoge"
        400:
          description: "失敗時のレスポンス"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "request bad error"
  /api/login/:
    post:
      tags: ["hikaru API"]
      summary: "ログインAPI"
      description: "ログイン情報を取得するAPI"
      parameters:
      - name: "mail"
        in: "query"
        description: "メールアドレス"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "ハッシュ化されたパスワード"
        required: true
        type: "string"
        format: "password"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              firstName:
                type: "string"
                example: "山田"
              lastName:
                type: "string"
                example: "太郎"
              firstNameKana:
                type: "string"
                example: "ヤマダ"
              lastNameKana:
                type: "string"
                example: "タロウ"
              phoneNumber:
                type: "integer"
                format: "int32"
                example: "09012345678"
        400:
          description: "パラメータエラー"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Bad Request"
        404:
          description: "ユーザー Not Found"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "User Not Found"
  /api/reserve/commit/:
    post:
      tags: ["hikaru API"]
      summary: "予約確定API"
      description: "予約を確定するAPI"
      parameters:
      - name: "menuId"
        in: "query"
        description: "予約メニューID"
        required: true
        type: "integer"
        format: "int32"
      - name: "isFirst"
        in: "query"
        description: "初回利用"
        required: true
        type: "boolean"
      - name: "isUsecoupon"
        in: "query"
        description: "クーポン利用"
        required: false
        type: "boolean"
      - name: "pregnancyTerm"
        in: "query"
        description: "妊娠有無<br>0:妊娠なし<br>1:4ヵ月未満<br>2:5ヵ月<br>3:6ヵ月<br>4:7ヵ月<br>5:8ヵ月<br>6:9ヵ月<br>7:10ヵ月"
        required: false
        type: "integer"
        enum: [0,1,2,3,4,5,6,7]
      - name: "children"
        in: "query"
        description: "お子様連れ<br>0:なし<br>1:1人<br>2:2人<br>3:3人<br>4:4人<br>5:5人以上"
        required: false
        type: "integer"
        enum: [0,1,2,3,4,5]
      - name: "isGetMessage"
        in: "query"
        description: "サロンからのメッセージを受け取るかどうか"
        required: false
        type: "boolean"
      - name: "request"
        in: "query"
        description: "サロンへのご要望・ご相談"
        required: false
        type: "string"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                example: "200"
        400:
          description: "パラメータエラー"
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                example: "400"
              error:
                type: "string"
                example: "Bad Request"
